---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-restricted-metrics
  namespace: {{.Namespace}}
  labels:
    app: namespace-restricted-metrics
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-restricted-metrics
  labels:
    platform.opendatahub.io/part-of: monitoring
  {{- if .DSCI }}
  ownerReferences:
  - apiVersion: {{.DSCI.APIVersion}}
    kind: {{.DSCI.Kind}}
    name: {{.DSCI.Name}}
    uid: {{.DSCI.UID}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odh:pod-metrics-reader
subjects:
  - kind: ServiceAccount
    name: namespace-restricted-metrics
    namespace: {{.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-restricted-metrics-auth-delegator
  labels:
    platform.opendatahub.io/part-of: monitoring
  {{- if .DSCI }}
  ownerReferences:
  - apiVersion: {{.DSCI.APIVersion}}
    kind: {{.DSCI.Kind}}
    name: {{.DSCI.Name}}
    uid: {{.DSCI.UID}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: namespace-restricted-metrics
    namespace: {{.Namespace}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-restricted-metrics-config
  namespace: {{.Namespace}}
  labels:
    app: namespace-restricted-metrics
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
data:
  kube-rbac-proxy.yaml: |
    authorization:
      rewrites:
        byQueryParameter:
          name: "namespace"
      resourceAttributes:
        apiVersion: metrics.k8s.io/v1beta1
        resource: pods
        namespace: "{{ "{{ .Value }}" }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-restricted-metrics
  namespace: {{.Namespace}}
  labels:
    app: namespace-restricted-metrics
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-restricted-metrics
  template:
    metadata:
      labels:
        app: namespace-restricted-metrics
    spec:
      serviceAccountName: namespace-restricted-metrics
      containers:
        # kube-rbac-proxy for authentication and authorization
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:9091/
            - --config-file=/etc/kube-rbac-proxy/kube-rbac-proxy.yaml
            - --tls-cert-file=/etc/tls/private/tls.crt
            - --tls-private-key-file=/etc/tls/private/tls.key
            - --logtostderr=true
            - --v=2
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: config
              mountPath: /etc/kube-rbac-proxy
              readOnly: true
            - name: tls
              mountPath: /etc/tls/private
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        # prom-label-proxy for namespace filtering
        - name: prom-label-proxy
          image: quay.io/prometheuscommunity/prom-label-proxy:v0.8.0
          args:
            - --insecure-listen-address=127.0.0.1:9091
            - --upstream=http://data-science-monitoringstack-prometheus.{{.Namespace}}.svc:9090
            - --label=namespace
            - --enable-label-apis
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      volumes:
        - name: config
          configMap:
            name: namespace-restricted-metrics-config
        - name: tls
          secret:
            secretName: namespace-restricted-metrics-tls
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: namespace-restricted-metrics
  namespace: {{.Namespace}}
  labels:
    app: namespace-restricted-metrics
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: namespace-restricted-metrics-tls
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: namespace-restricted-metrics
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: namespace-restricted-metrics
  namespace: {{.Namespace}}
  labels:
    app: namespace-restricted-metrics
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
spec:
  to:
    kind: Service
    name: namespace-restricted-metrics
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
