---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-tls-ca-copy
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-tls-ca-copy
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
  resourceNames: ["prometheus-web-tls-ca"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-tls-ca-copy
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-tls-ca-copy
subjects:
- kind: ServiceAccount
  name: prometheus-tls-ca-copy
  namespace: {{.Namespace}}
---
# Job to copy CA from ConfigMap to Secret (MonitoringStack requires Secret)
apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-web-tls-ca-copy
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
  ownerReferences:
  - apiVersion: {{.Component.APIVersion}}
    kind: {{.Component.Kind}}
    name: {{.Component.Name}}
    uid: {{.Component.UID}}
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: prometheus-tls-ca-copy
    spec:
      restartPolicy: OnFailure
      serviceAccountName: prometheus-tls-ca-copy
      containers:
        - name: copy-ca
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Waiting for CA ConfigMap to be populated..."
              while [ ! -f /ca-configmap/service-ca.crt ]; do
                echo "Waiting for service-ca.crt..."
                sleep 2
              done

              echo "Creating Secret from CA..."
              kubectl create secret generic prometheus-web-tls-ca \
                --from-file=service-ca.crt=/ca-configmap/service-ca.crt \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "CA Secret created successfully"
          volumeMounts:
            - name: ca-configmap
              mountPath: /ca-configmap
              readOnly: true
      volumes:
        - name: ca-configmap
          configMap:
            name: prometheus-web-tls-ca
